repos:
  # Backend Python hooks
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        files: ^backend/.*\.py$
        args: [--config=backend/pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^backend/.*\.py$
        args: [--settings-path=backend/pyproject.toml]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^backend/.*\.py$
        args: [--config=backend/setup.cfg]

  # Frontend JavaScript/TypeScript hooks
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: bash -c 'cd frontend && npm run lint:fix'
        language: system
        files: ^frontend/.*\.(ts|tsx)$
        pass_filenames: false

      - id: prettier
        name: Prettier
        entry: bash -c 'cd frontend && npm run format'
        language: system
        files: ^frontend/.*\.(ts|tsx)$
        pass_filenames: false